routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/403', function () {
    return view('403');
});


Auth::routes();

Route::group(['middleware'=>'auth'],function() {

    Route::get('/', 'HomeController@index');
    Route::get('/attendance', 'HomeController@attendance');
    //Route::get('/my/leaves', 'HomeController@myLeaves');
    Route::get('/my/profile', 'EmployeeController@show');
    Route::get('/home', 'HomeController@index')->name('home');
    

    //employee self feedback
    Route::get('/employee_feedback/{id}', 'EmployeePerformanceEvaluationController@index')->name('employee_feedback');
    Route::post('/employee_feedback', 'EmployeePerformanceEvaluationController@submitEmployeeFeedback')->name('self_feedback');

    //submit team evaluation
    Route::post('/employee_evaluation', 'EmployeePerformanceEvaluationController@evaluateEmployeeJobPerformance')->name('evaluate_performance');
    Route::get('/get/designation/{depttId}', 'EmployeeController@getDesignations');
    Route::get('/get/cities/{stateId}', 'EmployeeController@getCities');


    //employee evaluation list
    Route::get('/my/performance/evaluation/list', 'EmployeePerformanceEvaluationController@myPerformanceEvaluationFormList')->name('myPerformanceEvaluationList');
    Route::get('/team/performance/evaluation/list', 'EmployeePerformanceEvaluationController@myTeamPerformanceEvaluationList')->name('myTeamPerformanceEvaluationList');

     Route::get('/change/password', 'EmployeeController@show_change_password')->name('change.password');
     Route::post('/change/password', 'EmployeeController@change_password')->name('update.password');

    Route::group(['middleware'=>'hr'],function() {
        Route::resource('employee', 'EmployeeController', ['names'=>[
            'index' => 'employee.list',
            'create' => 'employee.new',
            'show/{employeeId}' => 'employee.view',
            'store' => 'employee.store',
        ]]);

        Route::resource('leave', 'LeaveController', ['names'=>[
            'index' => 'leave.list',
            'create' => 'leave.new',
            'show/{leaveId}' => 'leave.view',
            'store' => 'leave.store',
        ]]);

        Route::resource('department', 'DepartmentController', ['names'=>[
            'index' => 'department.list',
            'create' => 'department.new',
            'show/{departmentId}' => 'department.view',
            'store' => 'department.store',
        ]]);

        Route::resource('designation', 'DesignationController', ['names'=>[
            'index' => 'designation.list',
            'create' => 'designation.new',
            'show/{designationId}' => 'designation.view',
            'store' => 'designation.store',
        ]]);

        Route::resource('publicholiday', 'PublicHolidayController', ['names'=>[
            'index' => 'publicholiday.list',
            'create' => 'publicholiday.new',
            'show/{publicholidayId}' => 'publicholiday.view',
            'store' => 'publicholiday.store',
        ]]);

        Route::resource('states', 'StatesController', ['names'=>[
            'index' => 'states.list',
            'create' => 'states.new',
            'show/{statesId}' => 'states.view',
            'store' => 'states.store',
        ]]);

        Route::resource('project', 'ProjectController', ['names'=>[
            'index' => 'project.list',
            'create' => 'project.new',
            'show/{projectId}' => 'project.view',
            'store' => 'project.store',
        ]]);


        Route::resource('award', 'AwardController', ['names'=>[
            'index' => 'award.list',
            'create' => 'award.new',
            'show/{awardId}' => 'award.view',
            'store' => 'award.store',
        ]]);
        Route::get('/employee/performance/evaluation/list', 'EmployeePerformanceEvaluationController@emloyeePerformanceEvaluationList')->name('employeePerformanceEvaluationList');
    });


});



Route::get('employee/release/feedback_form', 'EmployeeController@releaseFeedbackForm');

app/Models/Project.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
     protected $table = 'projects';
     protected $primaryKey = 'id';
     protected $guarded = ['id'];
     protected $fillable = [
        'project_name', 'start_date', 'end_date', 'deadline_date'
    ];


	public function employees()
	{
	    return $this->belongsToMany('App\User', 'employee_projects', 'fk_projectId', 'fk_employeeId');
	}
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Project;
use App\Models\EmployeeProject;
use App\User;
use Session;
use Carbon\Carbon;
class ProjectController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projectList = Project::orderby('id', 'desc')->get();
         $today = Carbon::now()->format('Y-m-d');
        return view('project.list', compact('projectList', 'today'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $details = [];
        $assignedToEmployees = [];
        $allEmployees = User::whereNull('date_of_leaving')->orderBy('first_name', 'asc')->pluck('first_name', 'id')->toArray(); 
        return view('project.details', compact('details', 'allEmployees', 'assignedToEmployees'));    
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->input();
        $rules = [
            'project_name' => 'required',
            'start_date' => 'required|date',
            'deadline_date' => 'date|nullable|after:start_date',
            'end_date' => 'date|nullable|after:start_date',
        ];
        $employeeIds = $input['fk_employeeId'];
        $this->validate($request, $rules);
        unset($input['_token']);

        $projectDetails = Project::updateOrCreate(['id'=>$input['id']], $input);
        EmployeeProject::where('fk_projectId', $projectDetails['id'])->whereNotIn('fk_employeeId', $employeeIds)->delete();
        foreach($employeeIds as $employeeId){
        	EmployeeProject::firstOrCreate(['fk_projectId'=>$projectDetails['id'], 'fk_employeeId'=>$employeeId], ['fk_projectId'=>$projectDetails['id'], 'fk_employeeId'=>$employeeId]);
        }
        
        Session::flash('flash_message', 'Project details submitted');
        return redirect()->back();
    }
    /**
            }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $details = Project::find($id);
        $assignedToEmployees = $details->employees->pluck('id')->toArray();
        $allEmployees = User::orderBy('first_name', 'asc')->pluck('first_name', 'id')->toArray(); 
        return view('project.details', compact('details', 'allEmployees', 'assignedToEmployees'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project = Project::find($id);
        $project->employees()->detach();
        $project->delete();
        Session::flash('flash_message', 'Project deleted');
        return redirect()->back();
    }
}

resources/views/project/details.blade.php
@extends('layouts.master')
@section('content')
    <link href="{{url('bower_components/select2/dist/css/select2.min.css')}}" rel="stylesheet">
    <section class="content-header">
        <h1>
            &nbsp;
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Project Details</li>
        </ol>
    </section>

    <section class="content">
        @if(Session::has('flash_message'))
            <div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span><em> {!! session('flash_message') !!}</em></div>
        @endif
        <div class="row">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>
        <div class="row">
            <div class="col-md-12 ">
                <!-- general form elements -->
                <div class="box box-primary">
                    
                    <!-- /.box-header -->
                    <!-- form start -->

                    {{Form::model($details, array('url'=>route('project.store')))}}
                    <div class="box-body">
                        <div class="form-group col-md-12">
                            <label for="exampleInputEmail1">Project Name</label>
                            {{Form::text('project_name',  null, array('class'=>'form-control'))}}
                        </div>
                        <div class="form-group col-md-4">
                            <label for="exampleInputFile">Project Start Date</label> 
                            {{Form::text('start_date', null, array('class'=>'form-control datepicker', 'autocomplete'=>'off'))}}
                        </div>
                        <div class="form-group col-md-4">
                            <label for="exampleInputFile">Project End Date</label> 
                            {{Form::text('end_date', null, array('class'=>'form-control datepicker', 'autocomplete'=>'off'))}}
                        </div>
                        <div class="form-group col-md-4">
                            <label for="exampleInputFile">Project Deadline </label> 
                            {{Form::text('deadline', null, array('class'=>'form-control datepicker', 'autocomplete'=>'off'))}}
                        </div>
                       
                        <div class="form-group col-md-12">
                            <label for="exampleInputFile">Employees involved in project</label>
                            {{Form::select('fk_employeeId[]', $allEmployees, $assignedToEmployees, array('class'=>'form-control select2', 'multiple'=>'multiple', 'id'=>'employee', 'data-placeholder'=>'Select Employees'))}}
                        </div>                    
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        {{Form::hidden('id', null)}}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('scripts')
    <script src="{{url('bower_components/select2/dist/js/select2.full.min.js')}}"></script>
    <script src="{{url('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
    <script>
        $('.select2').select2();
        $('.datepicker').datepicker({format:'yyyy-mm-dd', autoclose: true});
    </script>
@endsection

resources/views/project/list.blade.php
@extends('layouts.master')
@section('content')
    <link rel="stylesheet" href="{{url('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
    <section class="content-header">
        <h1>
            &nbsp;
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Project List</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Project List</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <div class="box-body">
                        <table id="data" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Project</th>
                                <th>Start Date</th>
                                <th>Deadline Date</th>
                                <th>End Date</th>
                                <th>Status</th>
                                <th>View Details</th>
                                <th>Delete</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($projectList as $project)
                                <tr @if($project['end_date'] != null and $project['end_date'] <= $today) style="background-color: green; color:#fff;" @endif>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$project['project_name']}}</td>
                                    <td>@if($project['start_date'] != null){{\Carbon\Carbon::parse($project['start_date'])->format('d F, Y')}} @endif</td>
                                    <td>@if($project['deadline_date'] != null) {{\Carbon\Carbon::parse($project['deadline_date'])->format('d F, Y')}} @endif</td>
                                    <td>@if($project['end_date'] != null) {{\Carbon\Carbon::parse($project['end_date'])->format('d F, Y')}} @endif</td>
                                    <td>
                                        @if($project['end_date'] != null and $project['end_date'] <= $today) 
                                            @for($i=1; $i<=5;$i++)
                                                <i class="fa fa-2x fa-star star"></i>
                                            @endfor
                                        @else 
                                            In Progress
                                        @endif
                                    </td>
                                    <td>
                                        <a href="{{route('project.show', ['id'=>$project['id']])}}" class="btn btn-primary"> Edit Details</a>
                                    </td>
                                    <td>
                                        {{Form::open(array('url'=>route('project.destroy', ['project'=>$project]), 'method'=>'delete'))}}
                                            <input type="submit" class="btn btn-danger" value="Delete">
                                        {{Form::close()}}
                                    
                                    </td>
                                  
                                </tr>
                            @endforeach
                            </tbody>

                        </table>
                    </div>
                    <!-- /.box-body -->


                </div>
            </div>
        </div>
    </section>
@endsection

@section('scripts')
    <script src="{{url('bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{url('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script>
        $(function () {
            $('#data').DataTable({
                'paging'      : false,
                'lengthChange': false,
                'searching'   : true,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            })
        })
    </script>
@endsection