routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/403', function () {
    return view('403');
});


Auth::routes();

Route::group(['middleware'=>'auth'],function() {

    Route::get('/', 'HomeController@index');
    Route::get('/attendance', 'HomeController@attendance');
    //Route::get('/my/leaves', 'HomeController@myLeaves');
    Route::get('/my/profile', 'EmployeeController@show');
    Route::get('/home', 'HomeController@index')->name('home');
    

    //employee self feedback
    Route::get('/employee_feedback/{id}', 'EmployeePerformanceEvaluationController@index')->name('employee_feedback');
    Route::post('/employee_feedback', 'EmployeePerformanceEvaluationController@submitEmployeeFeedback')->name('self_feedback');

    //submit team evaluation
    Route::post('/employee_evaluation', 'EmployeePerformanceEvaluationController@evaluateEmployeeJobPerformance')->name('evaluate_performance');
    Route::get('/get/designation/{depttId}', 'EmployeeController@getDesignations');
    Route::get('/get/cities/{stateId}', 'EmployeeController@getCities');


    //employee evaluation list
    Route::get('/my/performance/evaluation/list', 'EmployeePerformanceEvaluationController@myPerformanceEvaluationFormList')->name('myPerformanceEvaluationList');
    Route::get('/team/performance/evaluation/list', 'EmployeePerformanceEvaluationController@myTeamPerformanceEvaluationList')->name('myTeamPerformanceEvaluationList');

     Route::get('/change/password', 'EmployeeController@show_change_password')->name('change.password');
     Route::post('/change/password', 'EmployeeController@change_password')->name('update.password');

    Route::group(['middleware'=>'hr'],function() {
        Route::resource('employee', 'EmployeeController', ['names'=>[
            'index' => 'employee.list',
            'create' => 'employee.new',
            'show/{employeeId}' => 'employee.view',
            'store' => 'employee.store',
        ]]);

        Route::resource('leave', 'LeaveController', ['names'=>[
            'index' => 'leave.list',
            'create' => 'leave.new',
            'show/{leaveId}' => 'leave.view',
            'store' => 'leave.store',
        ]]);

        Route::resource('department', 'DepartmentController', ['names'=>[
            'index' => 'department.list',
            'create' => 'department.new',
            'show/{departmentId}' => 'department.view',
            'store' => 'department.store',
        ]]);

        Route::resource('designation', 'DesignationController', ['names'=>[
            'index' => 'designation.list',
            'create' => 'designation.new',
            'show/{designationId}' => 'designation.view',
            'store' => 'designation.store',
        ]]);

        Route::resource('publicholiday', 'PublicHolidayController', ['names'=>[
            'index' => 'publicholiday.list',
            'create' => 'publicholiday.new',
            'show/{publicholidayId}' => 'publicholiday.view',
            'store' => 'publicholiday.store',
        ]]);

        Route::resource('states', 'StatesController', ['names'=>[
            'index' => 'states.list',
            'create' => 'states.new',
            'show/{statesId}' => 'states.view',
            'store' => 'states.store',
        ]]);

        Route::resource('project', 'ProjectController', ['names'=>[
            'index' => 'project.list',
            'create' => 'project.new',
            'show/{projectId}' => 'project.view',
            'store' => 'project.store',
        ]]);


        Route::resource('award', 'AwardController', ['names'=>[
            'index' => 'award.list',
            'create' => 'award.new',
            'show/{awardId}' => 'award.view',
            'store' => 'award.store',
        ]]);
        Route::get('/employee/performance/evaluation/list', 'EmployeePerformanceEvaluationController@emloyeePerformanceEvaluationList')->name('employeePerformanceEvaluationList');
    });


});



Route::get('employee/release/feedback_form', 'EmployeeController@releaseFeedbackForm');

app/Models/Award.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Award extends Model
{
    protected $table = 'awards';
     protected $primaryKey = 'id';
     protected $guarded = ['id'];
     protected $fillable = [
        'fk_employeeId', 'award_in_recognition_of', 'month_year', 'certificate'
    ];

    public function employee()
    {
        return $this->belongsTo('App\User','fk_employeeId','id');
    }
}

app/Http/Controllers/AwardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Award;
use App\User;
Use Carbon\Carbon;
use Str;
use Session;

class AwardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $awardList = Award::orderby('id', 'desc')->get();
        return view('award.list', compact('awardList'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $details = [];
        return view('award.details', compact('details'));    
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->input();
        $rules = [
            'fk_employeeId' => 'required',
            'award_in_recognition_of' => 'required',
            'month_year' => 'required',
            'certificate' =>'mimes:pdf',
        ];
        $this->validate($request, $rules);
        unset($input['_token']);
        if($request->hasFile('certificate')){
            $file = $request->file('certificate');
            $input['certificate'] = Str::random() .'.'. $file->getClientOriginalExtension();
            $file->move('employee_documents/'.$input['fk_employeeId'],$input['certificate']);
        }
        $dt = Carbon::createFromFormat('Y-m', $input['month_year']);
        $input['month_year']= $dt->endOfMonth()->format('Y-m-d');
        Award::updateOrCreate(['id'=>$input['id']], $input);
        Session::flash('flash_message', 'Award details submitted');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $details = Award::find($id);
        return view('award.details', compact('details'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
   
    public function destroy($id)
    {
         $award = Award::find($id);
         if($award['certificate'] != null){
            unlink('employee_documents/'.$award['fk_employeeId'].'/'.$award['certificate']);
         }
         
        $award->delete();
        Session::flash('flash_message', 'Award deleted');
        return redirect()->back();
    }
}

resources/views/award/details.blade.php
@extends('layouts.master')
@section('content')
    <link href="{{url('bower_components/select2/dist/css/select2.min.css')}}" rel="stylesheet">
    <style>
        .datepicker > div {
    display: block ;
}
    </style>
    <section class="content-header">
        <h1>
            &nbsp;
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Awards Details</li>
        </ol>
    </section>

    <section class="content">
        @if(Session::has('flash_message'))
            <div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span><em> {!! session('flash_message') !!}</em></div>
        @endif
        <div class="row">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>
        <div class="row">
            <div class="col-md-12 ">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Awards Details</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->

                    {{Form::model($details, array('url'=>route('award.store' ), 'files'=> true))}}
                    <div class="box-body">
                        <div class="form-group col-md-3">
                            <label for="exampleInputEmail1">Award In Recognition Of</label>
                            {{Form::text('award_in_recognition_of',  null, array('class'=>'form-control'))}}
                        </div>
                        
                        <div class="form-group col-md-3">
                            <label for="exampleInputFile">Employee</label>
                            {{Form::select('fk_employeeId', get_all_employees(), null, array('class'=>'form-control select2', 'id'=>'department', 'data-placeholder'=>'Select Employee'))}}
                        </div>

                        
                        @if($details != null)
                            <div class="form-group col-md-3">
                                <label for="exampleInputEmail1">Month</label>
                                {{Form::text('month_year',  \Carbon\Carbon::parse($details['month_year'])->format('Y-m'), array('class'=>'form-control form-control-1 input-sm from monthYearPicker', 'autocomplete'=>'off'))}}
                            </div>
                        @else
                            <div class="form-group col-md-3">
                                <label for="exampleInputEmail1">Month</label>
                                {{Form::text('month_year',  null, array('class'=>'form-control form-control-1 input-sm from monthYearPicker', 'autocomplete'=>'off'))}}
                            </div>
                        @endif
                        <div class="form-group col-md-3">
                            <label for="exampleInputFile">Certificate</label>
                            @if($details != null and isset($details['certificate'])) 
                                  <a  href="{{url('employee_documents/'.$details['fk_employeeId'].'/'.$details['certificate'])}}" target="_blank">
                                        <img src="{{url('dist/img/pdf.png')}}"><br>
                                           <span class="btn-xs btn-primary">View Certificate</span>
                                    </a><br>
                                @endif
                                <input type="file" name="certificate" accept="application/pdf">
                           
                        </div>

                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        {{Form::hidden('id', null)}}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('scripts')
    <script src="{{url('bower_components/select2/dist/js/select2.full.min.js')}}"></script>
     <script src="{{url('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
    <script>
        var startDate = new Date();
        $('.select2').select2();
        $('.monthYearPicker').datepicker({
            autoclose: true,
            minViewMode: 1,
            format: 'yyyy-mm'
        }).on('changeDate', function(selected){
        FromEndDate = new Date(selected.date.valueOf());
        FromEndDate.setDate(FromEndDate.getDate(new Date(selected.date.valueOf())));
        //$('.monthYearPicker').datepicker('setEndDate', FromEndDate);
      }); 
    </script>
@endsection

resources/views/award/list.blade.php
@extends('layouts.master')
@section('content')
    <link rel="stylesheet" href="{{url('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
    <section class="content-header">
        <h1>
            &nbsp;
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Award List</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Award List</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <div class="box-body"> <h3 class="text-center">Employee of the month</h3>
                           
                        <table id="data" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Appreciation For The Month Of</th>
                                <th>Name</th>
                                <th>Department</th>
                                <th>Award In recognition of</th>
                                <th>Certificate</th>
                                <th>View/Edit Details</th>
                                <th>Delete</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($awardList as $award)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{\Carbon\Carbon::parse($award['month_year'])->format(' F, Y')}}</td>
                                    <td>{{$award->employee->first_name}}</td>
                                    <td>@if(isset($award->employee->department->name)) {{$award->employee->department->name}}@endif</td>
                                    <td>{{$award['award_in_recognition_of']}}</td>
                                    <td>
                                        
                                         @if(isset($award['certificate'])) 
                                  <a  href="{{url('employee_documents/'.$award['fk_employeeId'].'/'.$award['certificate'])}}" target="_blank">
                                        <img src="{{url('dist/img/pdf.png')}}" height=50><br>
                                           <span class="btn-xs btn-primary">View Certificate</span>
                                    </a><br>
                                @endif
                                    </td>
                                    <td><a href="{{route('award.show', ['id'=>$award['id']])}}" class="btn btn-primary"> Edit</a></td>
                                    <td>
                                        {{Form::open(array('url'=>route('award.destroy', ['award'=>$award]), 'method'=>'delete'))}}
                                            <input type="submit" class="btn btn-danger" value="Delete">
                                        {{Form::close()}}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>

                        </table>
                    </div>
                    <!-- /.box-body -->


                </div>
            </div>
        </div>
    </section>
@endsection

@section('scripts')
    <script src="{{url('bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{url('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script>
        $(function () {
            $('#data').DataTable({
                'paging'      : false,
                'lengthChange': false,
                'searching'   : true,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            })
        })
    </script>
@endsection