routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/403', function () {
    return view('403');
});


Auth::routes();

Route::group(['middleware'=>'auth'],function() {

    Route::get('/', 'HomeController@index');
    Route::get('/attendance', 'HomeController@attendance');
    //Route::get('/my/leaves', 'HomeController@myLeaves');
    Route::get('/my/profile', 'EmployeeController@show');
    Route::get('/home', 'HomeController@index')->name('home');
    

    //employee self feedback
    Route::get('/employee_feedback/{id}', 'EmployeePerformanceEvaluationController@index')->name('employee_feedback');
    Route::post('/employee_feedback', 'EmployeePerformanceEvaluationController@submitEmployeeFeedback')->name('self_feedback');

    //submit team evaluation
    Route::post('/employee_evaluation', 'EmployeePerformanceEvaluationController@evaluateEmployeeJobPerformance')->name('evaluate_performance');
    Route::get('/get/designation/{depttId}', 'EmployeeController@getDesignations');
    Route::get('/get/cities/{stateId}', 'EmployeeController@getCities');


    //employee evaluation list
    Route::get('/my/performance/evaluation/list', 'EmployeePerformanceEvaluationController@myPerformanceEvaluationFormList')->name('myPerformanceEvaluationList');
    Route::get('/team/performance/evaluation/list', 'EmployeePerformanceEvaluationController@myTeamPerformanceEvaluationList')->name('myTeamPerformanceEvaluationList');

     Route::get('/change/password', 'EmployeeController@show_change_password')->name('change.password');
     Route::post('/change/password', 'EmployeeController@change_password')->name('update.password');

    Route::group(['middleware'=>'hr'],function() {
        Route::resource('employee', 'EmployeeController', ['names'=>[
            'index' => 'employee.list',
            'create' => 'employee.new',
            'show/{employeeId}' => 'employee.view',
            'store' => 'employee.store',
        ]]);

        Route::resource('leave', 'LeaveController', ['names'=>[
            'index' => 'leave.list',
            'create' => 'leave.new',
            'show/{leaveId}' => 'leave.view',
            'store' => 'leave.store',
        ]]);

        Route::resource('department', 'DepartmentController', ['names'=>[
            'index' => 'department.list',
            'create' => 'department.new',
            'show/{departmentId}' => 'department.view',
            'store' => 'department.store',
        ]]);

        Route::resource('designation', 'DesignationController', ['names'=>[
            'index' => 'designation.list',
            'create' => 'designation.new',
            'show/{designationId}' => 'designation.view',
            'store' => 'designation.store',
        ]]);

        Route::resource('publicholiday', 'PublicHolidayController', ['names'=>[
            'index' => 'publicholiday.list',
            'create' => 'publicholiday.new',
            'show/{publicholidayId}' => 'publicholiday.view',
            'store' => 'publicholiday.store',
        ]]);

        Route::resource('states', 'StatesController', ['names'=>[
            'index' => 'states.list',
            'create' => 'states.new',
            'show/{statesId}' => 'states.view',
            'store' => 'states.store',
        ]]);

        Route::resource('project', 'ProjectController', ['names'=>[
            'index' => 'project.list',
            'create' => 'project.new',
            'show/{projectId}' => 'project.view',
            'store' => 'project.store',
        ]]);


        Route::resource('award', 'AwardController', ['names'=>[
            'index' => 'award.list',
            'create' => 'award.new',
            'show/{awardId}' => 'award.view',
            'store' => 'award.store',
        ]]);
        Route::get('/employee/performance/evaluation/list', 'EmployeePerformanceEvaluationController@emloyeePerformanceEvaluationList')->name('employeePerformanceEvaluationList');
    });


});



Route::get('employee/release/feedback_form', 'EmployeeController@releaseFeedbackForm');

app/Http/Controllers/LeaveController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\EmployeeLeave;
use App\User;
use Carbon\Carbon;
use Session;
use Illuminate\Support\Facades\Input;
use DB;

class LeaveController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $details = Input::get();
        $employeeList = get_employee_list();
        $leaveList = EmployeeLeave::orderBy('leave_date', 'desc');
        if(isset($details['fk_employeeId'])){$leaveList = $leaveList->where('fk_employeeId', $details['fk_employeeId']);}
        if(isset($details['leave_type'])){$leaveList = $leaveList->where('leave_type', $details['leave_type']);}
        if(isset($details['leave_date'])){$leaveList = $leaveList->where('leave_date', Carbon::parse($details['leave_date'])->format('Y-m-d'));}
        $leaveList = $leaveList->paginate(20);
        return view('leaves.list', compact('leaveList', 'details', 'employeeList'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $details = [];
        $employeeList = [''=>''] + User::pluck('first_name', 'id')->toArray();
        return view('leaves.add', compact('employeeList', 'details'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->input();
        $rules = [
            'leave_date' => ['required', 'date'],
            'fk_employeeId' => ['required'],
            'leave_type' => 'required',
            'is_paid' => 'required',
        ];
        $this->validate($request, $rules);
        unset($input['_token']);
        $input['leave_date'] = Carbon::parse($input['leave_date'])->format('Y-m-d');
        if($input['id'] == null){
            EmployeeLeave::updateOrCreate(['leave_date'=>$input['leave_date'], 'fk_employeeId'=>$input['fk_employeeId']], $input);
        }else{
            EmployeeLeave::updateOrCreate(['id'=>$input['id']], $input);
        }
        Session::flash('flash_message', 'Leave details submitted');
        return redirect(url('leave'));
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $details = EmployeeLeave::find($id);
        $employeeList = [''=>''] + User::pluck('first_name', 'id')->toArray();
        return view('leaves.add', compact('employeeList', 'details'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $leave = EmployeeLeave::find($id);
        $leave->delete();
        Session::flash('flash_message', 'Leave details deleted');
        return redirect()->back();
    }
}

resources/views/leaves/add.blade.php
@extends('layouts.master')
@section('content')
    <link href="{{url('bower_components/select2/dist/css/select2.min.css')}}" rel="stylesheet">
    <link href="{{url('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}" rel="stylesheet">
    <section class="content-header">
        <h1>
            Leave
            <small> Details</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Leave Details</li>
        </ol>
    </section>

    <section class="content">
        @if(Session::has('flash_message'))
            <div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span><em> {!! session('flash_message') !!}</em></div>
        @endif
        <div class="row">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>
        <div class="row">
            <div class="col-md-12 ">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Leave Details</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->

                    {{Form::model($details, array('url'=>route('leave.store')))}}
                    <div class="box-body">
                        <div class="form-group  col-md-3">
                            <label for="exampleInputEmail1">Select Employee</label>
                            {{Form::select('fk_employeeId', $employeeList, null, array('class'=>'form-control select2', 'data-placeholder'=>'Select Employee'))}}
                        </div>

                        <div class="form-group col-md-3">
                            <label for="exampleInputEmail1">Leave Types</label>
                            {{Form::select('leave_type', leave_types(), null, array('class'=>'form-control select2', 'data-placeholder'=>'Select Leave Type'))}}
                        </div>

                        <div class="form-group col-md-2">
                            <label>Leave Date:</label>
                            <div class="input-group date">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                {{Form::text('leave_date', null, array('class'=>'form-control pull-right datepicker_new', 'autocomplete'=>'off'))}}
                            </div>
                            <!-- /.input group -->
                        </div>
                        <div class="form-group col-md-2">
                            <label for="exampleInputEmail1">Paid</label>
                            <div class="checkbox">
                                {!! Form::radio('is_paid', 1, TRUE) !!} Yes
                                {!! Form::radio('is_paid', 0, TRUE) !!} No
                            </div>
                        </div>
                        <div class="form-group col-md-2">
                            <label for="exampleInputEmail1">Planned</label>
                            <div class="checkbox">
                                {!! Form::radio('is_planned', 1, TRUE) !!} Yes
                                {!! Form::radio('is_planned', 0, TRUE) !!} No
                            </div>
                        </div>

                        <div class="form-group col-md-12">
                            <label for="exampleInputFile">Leave Reason</label>
                            {{Form::text('leave_reason', null, array('class'=>'form-control'))}}
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        {{Form::hidden('id', null)}}
                        <button type="submit" class="btn btn-primary pull-right">Submit</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
@endsection

@section('scripts')
    <script src="{{url('bower_components/select2/dist/js/select2.full.min.js')}}"></script>
    <script src="{{url('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
    <script>
        $('.select2').select2();
        //fetchDesignation();
        $(document).on("change","#department",{target : $("#designation")},fetchDesignation);
        function fetchDesignation(event)
        {
            var depttId = $(this).val();
            var designationInput = event.data.target;
            var URL = window.location.origin+'/';
            var options = '<option></option>';
            $.ajax({
                url : URL+"get/designation/"+depttId,
                type: 'get',
                success : function(response){
                    var designation = response;
                    $.each(designation,function(id,val){
                        options += "<option value='"+id+"'>"+val+"</option>";
                    })
                },
                complete: function(){
                    designationInput.html(options);
                    designationInput.select2();
                }
            });
        }

       // $('.datepicker').datepicker({format:'dd-mm-yyyy',  startDate: new Date()});
        $('.datepicker_new').datepicker({format:'dd-mm-yyyy', autoclose: true});
    </script>
@endsection

resources/views/leaves/list.blade.php
@extends('layouts.master')
@section('content')
    <link rel="stylesheet" href="{{url('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
    <link href="{{url('bower_components/select2/dist/css/select2.min.css')}}" rel="stylesheet">
    <link href="{{url('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}" rel="stylesheet">
    <section class="content-header">
        <h1>
            Employee
            <small> Leave List</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Employee Leave List</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                @if(Session::has('flash_message'))
                    <div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span><em> {!! session('flash_message') !!}</em></div>
                @endif
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Leave List</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <div class="box-body">
                        <div class="row">
                            {{Form::model($details, array('method'=>'get'))}}
                                <div class="form-group col-md-3">
                                    <label for="exampleInputEmail1">Select Employee</label>
                                    {{Form::select('fk_employeeId', $employeeList, null, array('class'=>'form-control select2', 'data-placeholder'=>'Select Employee'))}}
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="exampleInputEmail1">Leave Types</label>
                                    {{Form::select('leave_type', leave_types(), null, array('class'=>'form-control select2', 'data-placeholder'=>'Select Leave Type'))}}
                                </div>
                                <div class="form-group col-md-3">
                                    <label>Leave Date:</label>
                                    <div class="input-group date">
                                        <div class="input-group-addon">
                                            <i class="fa fa-calendar"></i>
                                        </div>
                                        {{Form::text('leave_date', null, array('class'=>'form-control pull-right datepicker', 'autocomplete'=>'off'))}}
                                    </div>
                                </div>
                                <div class="form-group col-md-3 " style="padding-top: 22px;">
                                    <input type="submit" class="btn btn-primary" value="Search">
                                    <a href="{{url(route('leave.list'))}}" class="btn btn-success"><i class="fa fa-refresh"></i> Clear Filters</a>
                                </div>
                            {{Form::close()}}
                        </div>
                        <table id="data" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>Leave Date</th>
                                <th>Employee</th>
                                <th>Leave Type</th>
                                <th>Planned</th>                                
                                <th>Reason</th>
                                <th>Edit Details</th>
                                <th>Delete</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($leaveList as $leave)
                                <tr>
                                    <td>{{\Carbon\Carbon::parse($leave['leave_date'])->format('d-M-Y')}}</td>
                                    <td>{{$leave->employee->first_name .' '.$leave->employee->last_name}}<br>
                                         @if(isset($leave->employee->department->department)) <strong> Department : </strong> {{$leave->employee->department->department}} @endif <br>
                                         @if(isset($leave->employee->designation->designation)) <strong> Designation :</strong> {{$leave->employee->designation->designation}} @endif
                                    </td>
                                    <td>{{leave_types($leave['leave_type'])}} - {{paid_types($leave['is_paid'])}}</td>
                                    <td>@if($leave['is_planned'] == 1) YES @else NO @endif</td>
                                    <td>{{$leave['leave_reason']}}</td>
                                    <td><a href="{{route('leave.show', ['id'=>$leave['id']])}}" class="btn btn-primary"> Edit Details</a></td>
                                    <td>
                                        {{Form::open(array('url'=>route('leave.destroy', ['leave'=>$leave]), 'method'=>'delete'))}}
                                            <input type="submit" class="btn btn-danger" value="Delete">
                                        {{Form::close()}}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>

                        </table>
                        <div class="pagination pull-right">{{$leaveList->links()}}</div>
                    </div>
                    <!-- /.box-body -->


                </div>
            </div>
        </div>
    </section>
@endsection

@section('scripts')
    <script src="{{url('bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{url('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{url('bower_components/select2/dist/js/select2.full.min.js')}}"></script>
    <script src="{{url('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
    <script>
        $('.select2').select2();
        $(function () {
            $('#data').DataTable({
                'paging'      : false,
                'lengthChange': false,
                'searching'   : false,
                'ordering'    : true,
                'info'        : false,
                'autoWidth'   : false
            })
        })
        $('.datepicker').datepicker({format:'dd-mm-yyyy', autoclose: true});
    </script>
@endsection