routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/403', function () {
    return view('403');
});


Auth::routes();

Route::group(['middleware'=>'auth'],function() {

    Route::get('/', 'HomeController@index');
    Route::get('/attendance', 'HomeController@attendance');
    //Route::get('/my/leaves', 'HomeController@myLeaves');
    Route::get('/my/profile', 'EmployeeController@show');
    Route::get('/home', 'HomeController@index')->name('home');
    

    //employee self feedback
    Route::get('/employee_feedback/{id}', 'EmployeePerformanceEvaluationController@index')->name('employee_feedback');
    Route::post('/employee_feedback', 'EmployeePerformanceEvaluationController@submitEmployeeFeedback')->name('self_feedback');

    //submit team evaluation
    Route::post('/employee_evaluation', 'EmployeePerformanceEvaluationController@evaluateEmployeeJobPerformance')->name('evaluate_performance');
    Route::get('/get/designation/{depttId}', 'EmployeeController@getDesignations');
    Route::get('/get/cities/{stateId}', 'EmployeeController@getCities');


    //employee evaluation list
    Route::get('/my/performance/evaluation/list', 'EmployeePerformanceEvaluationController@myPerformanceEvaluationFormList')->name('myPerformanceEvaluationList');
    Route::get('/team/performance/evaluation/list', 'EmployeePerformanceEvaluationController@myTeamPerformanceEvaluationList')->name('myTeamPerformanceEvaluationList');

     Route::get('/change/password', 'EmployeeController@show_change_password')->name('change.password');
     Route::post('/change/password', 'EmployeeController@change_password')->name('update.password');

    Route::group(['middleware'=>'hr'],function() {
        Route::resource('employee', 'EmployeeController', ['names'=>[
            'index' => 'employee.list',
            'create' => 'employee.new',
            'show/{employeeId}' => 'employee.view',
            'store' => 'employee.store',
        ]]);

        Route::resource('leave', 'LeaveController', ['names'=>[
            'index' => 'leave.list',
            'create' => 'leave.new',
            'show/{leaveId}' => 'leave.view',
            'store' => 'leave.store',
        ]]);

        Route::resource('department', 'DepartmentController', ['names'=>[
            'index' => 'department.list',
            'create' => 'department.new',
            'show/{departmentId}' => 'department.view',
            'store' => 'department.store',
        ]]);

        Route::resource('designation', 'DesignationController', ['names'=>[
            'index' => 'designation.list',
            'create' => 'designation.new',
            'show/{designationId}' => 'designation.view',
            'store' => 'designation.store',
        ]]);

        Route::resource('publicholiday', 'PublicHolidayController', ['names'=>[
            'index' => 'publicholiday.list',
            'create' => 'publicholiday.new',
            'show/{publicholidayId}' => 'publicholiday.view',
            'store' => 'publicholiday.store',
        ]]);

        Route::resource('states', 'StatesController', ['names'=>[
            'index' => 'states.list',
            'create' => 'states.new',
            'show/{statesId}' => 'states.view',
            'store' => 'states.store',
        ]]);

        Route::resource('project', 'ProjectController', ['names'=>[
            'index' => 'project.list',
            'create' => 'project.new',
            'show/{projectId}' => 'project.view',
            'store' => 'project.store',
        ]]);


        Route::resource('award', 'AwardController', ['names'=>[
            'index' => 'award.list',
            'create' => 'award.new',
            'show/{awardId}' => 'award.view',
            'store' => 'award.store',
        ]]);
        Route::get('/employee/performance/evaluation/list', 'EmployeePerformanceEvaluationController@emloyeePerformanceEvaluationList')->name('employeePerformanceEvaluationList');
    });


});



Route::get('employee/release/feedback_form', 'EmployeeController@releaseFeedbackForm');

app/Models/State.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    protected $table = 'states';
    protected $primaryKey = 'id';
    protected $guarded = ['id'];
}

app/Http/Controllers/StatesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\State;
use Session;

class StatesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $statesList = State::orderby('id', 'desc')->get();
        return view('states.list', compact('statesList'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $details = [];
        return view('states.details', compact('details'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->input();
        $rules = [
            'state_name' => 'required',
        ];
        $this->validate($request, $rules);
        unset($input['_token']);

        State::updateOrCreate(['id'=>$input['id']], $input);
        Session::flash('flash_message', 'State submitted');
        return redirect('states');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $details = State::find($id);
        return view('states.details', compact('details'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $states = State::find($id);
        $states->delete();
        Session::flash('flash_message', 'State deleted');
        return redirect()->back();
    }
}

resources/views/states/details.blade.php
@extends('layouts.master')
@section('content')
    <link href="{{url('bower_components/select2/dist/css/select2.min.css')}}" rel="stylesheet">
    <section class="content-header">
       <h1>
            &nbsp;
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">States Details</li>
        </ol>
    </section>

    <section class="content">
        @if(Session::has('flash_message'))
            <div class="alert alert-success"><span class="glyphicon glyphicon-ok"></span><em> {!! session('flash_message') !!}</em></div>
        @endif
        <div class="row">
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
        </div>
        <div class="row">
            <div class="col-md-12 ">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">States Details</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->

                    {{Form::model($details, array('url'=>route('states.store')))}}
                        <div class="box-body">
                            <div class="form-group col-md-8">
                                <label for="exampleInputFile">Select State</label>
                                {{Form::text('state_name',null, array('class'=>'form-control'))}}
                            </div>


                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            {{Form::hidden('id', null)}}
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
    </section>
@endsection

@section('scripts')
    <script src="{{url('bower_components/select2/dist/js/select2.full.min.js')}}"></script>
    <script>
        $('.select2').select2();
        //fetchDesignation();
        $(document).on("change","#department",{target : $("#designation")},fetchDesignation);
        function fetchStates(event)
        {
            var depttId = $(this).val();
            var statesInput = event.data.target;
            var URL = window.location.origin+'/';
            var options = '<option></option>';
            $.ajax({
                url : URL+"get/designation/"+depttId,
                type: 'get',
                success : function(response){
                    var states = response;
                    $.each(states,function(id,val){
                        options += "<option value='"+id+"'>"+val+"</option>";
                    })
                },
                complete: function(){
                    statesInput.html(options);
                    statesInput.select2();
                }
            });
        }
    </script>
@endsection

resources/views/states/list.blade.php
@extends('layouts.master')
@section('content')
    <link rel="stylesheet" href="{{url('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
    <section class="content-header">
        <h1>
            &nbsp;
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">States List</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">States List</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <div class="box-body">
                        <table id="data" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>States</th>
                                <th>View Details</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($statesList as $states)
                                <tr>
                                    <td>{{$states['id']}}</td>
                                    <td>{{$states['state_name']}}</td>
                                    <td><a href="{{route('states.show', ['id'=>$states['id']])}}" class="btn btn-primary"> View Details</a></td>
                                    <td>
                                        {{Form::open(array('url'=>route('states.destroy', ['states'=>$states]), 'method'=>'delete'))}}
                                        <input type="submit" class="btn btn-danger" value="Delete">
                                        {{Form::close()}}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>

                        </table>
                    </div>
                    <!-- /.box-body -->


                </div>
            </div>
        </div>
    </section>
@endsection

@section('scripts')
    <script src="{{url('bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script src="{{url('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script>
        $(function () {
            $('#data').DataTable({
                'paging'      : true,
                'lengthChange': false,
                'searching'   : true,
                'ordering'    : true,
                'info'        : true,
                'autoWidth'   : false
            })
        })
    </script>
@endsection